### ISSUE TITLE
Enable CWYD to accept user input as speech in multiple languages. 

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/chat-with-your-data-solution-accelerator#317]
# Motivation

To allow users to chat with their data using speech in addition to just text. This speech input should support the following non-English languages: Swiss German: gsw-CH, German: de-CH, French: fr-CH, Italian: it-CH. 

# How would you feel if this feature request was implemented?
This will empower users to not only use speech as an input, but they can do it in multiple languages. 

# Requirements

- Users should be able to use speech as an input in non English languages to chat with their data.
- CWYD should respond in the same language as the input when the input is non-English.
- The non-English languages to be supported are:  Swiss German: gsw-CH, German: de-CH, French: fr-CH, Italian: it-CH

# Tasks

- [x] #549
- [x] Add frontend unit tests to the tests github action. #703
- [x] Accept the languages as a config input during deployment, rather than hardcoding them. #660
- [x] Edit the CWYD prompt to respond to the user in the same language as the input. (this is already in the prompt, and will be reintroduced via #645 )
