### ISSUE TITLE
Add E2E test suite

### ISSUE THREAD

**Issue by adamdougal** [Azure-Samples/chat-with-your-data-solution-accelerator#419]
# Motivation

To have ultimate confidence that changes are non-breaking, an E2E test suite should be added. This would reduce the manual testing burden when reviewing PR's, expecially dependabot.

# How would you feel if this feature request was implemented?

![nice](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHhkem9haGx6NjV5MGF0ODNpNHVwcGgzZHVpZjFhajVrYzR2MThhZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ZYKLgA1pB1WSPQASCs/giphy.gif)

# Requirements

- E2E tests that run against a deployed fully integrated version of the accelerator
- Only add a test for the default setup, where the front end calls `/api/conversation/custom`
  - This may require us to also test the uploading of documents via the admin application 
- Should run for every PR but only after the repository maintainers have approved the run due to security concerns https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories

# Tasks

_To be filled in by the engineer picking up the issue_

- [x] Create ADR for which framework to use, and pick one. 
- [x] Create scaffolding for first E2E test.
- [x] Write the first E2E test where the front end calls `/api/conversation/custom`
- [ ] Set up the test to run on merge and on PR. - blocked on #563. This work is covered in #564.
