### ISSUE TITLE
Upgrade Docker Build

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/chat-with-your-data-solution-accelerator#605]
# Motivation

We currently build and push the 3 docker images on a commit to main. This means you could break the main build without knowing. Amending this will show Pull Request Authors problems earlier.

# How would you feel if this feature request was implemented?

![image](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeWxqZG1hcnh2OHM5dW1jdTA4Y2J6Z2ZweWphdjdpdWh0djBlZDJuMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/6AFldi5xJQYIo/giphy.gif)

# Requirements

A list of requirements to consider this feature delivered
- We should build the docker images when the Tests pass on all branches
- We should however only push when we are on main.
- We should move the current bash scripts to use this action https://github.com/docker/build-push-action
- We should parameterise the name of the Container Registry that we are publishing too.
- Add the following vscode extension: -  github.vscode-github-actions

# Tasks

_To be filled in by the engineer picking up the issue_

- [x] Replace existing scripts with official docker GitHub action. #[710](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/710)
- [ ] Parameterize name of the registry [#712](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/712) 
- [ ] Create GitHub actions to do docker build without push on PR creation. [#712](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/712) 
- [ ] Add GitHub actions VSCode extension (This is already present in the [devcontainer configuration](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/74352f234b29cbf1aace7d01c7adb311d7100e43/.devcontainer/devcontainer.json#L23))
