### ISSUE TITLE
Configure logging for the application

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#637]
# Motivation

Configure logging for the application properly. Configure an application logger, as logs with `print()` do not seem to get sent to App Insights. Also configure log level, as by default Flask sets the log level to Warning.

https://flask.palletsprojects.com/en/2.3.x/logging/

# Requirements

A list of requirements to consider this feature delivered
- User `logger` instead of print statements within app
- Add useful log statements to application
- Configure log level to INFO

# Tasks

- [x] Switch print statements to logger - https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/640
- [x] Add additional useful log statements - https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/641/
- [x] Set log level to INFO - https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/642
