### ISSUE TITLE
Implement endpoint switch to custom

### ISSUE THREAD

**Issue by reechamishra** [Azure-Samples/chat-with-your-data-solution-accelerator#650]
# Motivation

Implement capability to switch endpoint to `custom` or `byod` based on `env` config to give flexibility to users for their needs.

# How would you feel if this feature request was implemented?

Amazing

# Requirements

As a chat user I want to switch between "On Your Data" endpoint to a "Custom" endpoint through configuration so that I can understand how to customise the solution for my own needs

# Tasks

_To be filled in by the engineer picking up the issue_

- [x] Introduce a new env variable to choose between custom or byod conversation type.
- [x] Use that new variable in create_app.py and create a new REST binding.
- [ ] Make changes to frontend to honour the new binding.
