### ISSUE TITLE
Enhancing Search : Semantic, Vector, Hybrid 

### ISSUE THREAD

**Issue by reechamishra** [Azure-Samples/chat-with-your-data-solution-accelerator#658]
# Motivation

To enhance the search capability on both endpoints to have semantic, vector or Hybrid search . 

# How would you feel if this feature request was implemented?

Empowered 

# Requirements

- Users should be able to implement hybrid, semantic or vector search based on their requirement 
- Custom endpoint already contains Hybrid search , however BYOD needs hybrid. 

# Tasks

_To be filled in by the engineer picking up the issue_

- [x] https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/449
- [x] https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/534
- [x] https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/517
- [x] https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/295
- [x] #650 
- [ ] #897

**Comment by ross-p-smith** [comment]
Closing this and leaving the remaining task open
