### ISSUE TITLE
Generate and store image embeddings in search index

### ISSUE THREAD

**Issue by adamdougal** [Azure-Samples/chat-with-your-data-solution-accelerator#748]
Required by https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/323

# Description

Generate image embeddings using computer vision and store them in a modified search index.

# Tasks

- [x] Investigate what needs to change with the search index and how to encorporate that into CWYDSA
  - [x] POC: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/786
  - [x] ADR: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/788
- [x] Add functional test for current index creation - https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/802
- [x] Stop using Langchain for creating, populating and searching index - https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/827
- [x] Generate image embeddings using computer vision - https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/892
- [x] Store image embeddings in search index - https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/921

**Comment by adamdougal** [comment]
**Update 26th April:**

- I'm investigating what changes are going to be required to the app code and index to be able to store and query an additional image embedding
- I've hit a problem where it does not appear that LangChain has support for Azure AI Computer Vision OR has the ability to query AzureSearch for more than one vector embedding.
- One option that _might_ work is to have two separate indexes and combine the search results in the application code. I'm not 100% sure if this is viable as yet
- Another option is to remove the use of LangChain in the [QuestionAnswerTool ](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/code/backend/batch/utilities/tools/QuestionAnswerTool.py)and [AzureSearchHelper](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/code/backend/batch/utilities/helpers/AzureSearchHelper.py)
  - We would still keep the LangChain orchestration option, but it would only be used in the [LangChainAgent](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/code/backend/batch/utilities/orchestrator/LangChainAgent.py)
  - This has also been done (for now) in the [azure-sample-openai-demo](https://github.com/Azure-Samples/azure-search-openai-demo/pull/738) repo
  - **Benefits:**
    - This would give us full control over how we query and store data in Azure AI Search
    - We wouldn't be blocked on LangChain updates to use the latest features from OpenAI and Azure
    - Potentially simpler code base
  - **Downsides:**
    - Potentially significant **breaking changes** required

My next steps are to investigate if removing LangChain allows easier integration of vision as well as seeing what else it might affect. If all goes well, I'll raise an ADR to discuss futher with the team.

**Comment by adamdougal** [comment]
**Update 1st May:**
- We are proceeding with removing LangChain from the tools
- Before starting to make this change, I am going to expand the current functional tests to ensure we are testing index creation. This will help ensure no unexpected changes are being made to the index.

**Comment by adamdougal** [comment]
**13th May:**

Mini code review:

- [ ] Make Computer Vision versions configurable
- [ ] Include original exception when catching and throwing
- [ ] Move inline patches to annotations


Get wider feedback:
- [ ] The use of `pytest-httpserver` in unit tests

**Comment by adamdougal** [comment]
**14th May Update:**

- A PR has been raised to add the call to computer vision to generate embeddings of the images
- Next steps are to take these embeddings and store them in a modified index
