### ISSUE TITLE
Make orchestration async

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#757]
Required by #320 

# Description

Semantic Kernel is async, therefore `Orchestrator.handle_message` needs to be asynchronous.

# Tasks

_To be filled in by the engineer picking up the subtask

- [x] Update `Orchestrator.handle_message` to be async, including all functions within
- [x] Test `/custom` endpoint
- [x] Test Teams extension
- [x] Update tests
