### ISSUE TITLE
Publish this template to azure samples browser

### ISSUE THREAD

**Issue by hemarina** [Azure-Samples/chat-with-your-data-solution-accelerator#760]
# Motivation

Since this is a "msft" authorized template in Azure-Samples, we may want to publish it to Microsoft learning page: [Onboarding Samples to learn.microsoft.com/samples](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main)

# Tasks

- [ ] Check metada in readmd. This template is not in azure-samples: https://learn.microsoft.com/en-us/samples/browse/?expanded=azure&languages=azdeveloper&terms=Chat%20with%20your%20Data%20Solution%20Accelerator
- [ ] Submit online form
- [ ] Check if this template is in azure-samples browser
- [ ] Example PRs can be found in https://github.com/Azure/awesome-azd/issues/281

**Comment by ross-p-smith** [comment]
@hemarina - I'm happy with the change related to this. I do think you need to add a new product to the Samples Explorer called `azure-ai-search` as this is the new marketing name for `azure-cognitive-search`

**Comment by ross-p-smith** [comment]
This is still not published in the Azure Samples Browser. Contact the OP and find out what is left to do

**Comment by ross-p-smith** [comment]
Now in Samples explorer
