### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by reechamishra** [Azure-Samples/chat-with-your-data-solution-accelerator#835]
# Motivation

This issue is to created to Track all Testing tasks on this repo 

# How would you feel if this feature request was implemented?

# Requirements

A list of requirements to consider this feature delivered

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/564)
- [ ] (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/541)
- [ ] (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/512)
- [ ] (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/801)
